export type CircularId = "2025/4" | "2023/5";

export type SourceRef = { circular: CircularId; article: string; paragraph?: string };
export type Step = { title: string; detail: string; checks: string[]; source: SourceRef };
export type Process = {
  id: string; title: string; aliases: string[]; category: string; circular: CircularId;
  article: string; registration: "Tescile tabi" | "Tescile tabi değil" | "Duruma göre";
  summary: string; roles: string[]; documents: string[]; officeChecks: string[];
  fieldChecks: string[]; outputs: string[]; warnings: string[]; steps: Step[];
};

const common2025 = (article: string): Step[] => [
  { title: "Başvuru ve ön inceleme", detail: "Talep ve işlem dosyasının mevzuata uygunluğu incelenir.", checks: ["Talep sahibinin ilgisini doğrula", "İşlem dosyasını ve eklerini kontrol et", "Kaynak belgeleri fen kayıt numarasıyla ilişkilendir"], source: { circular: "2025/4", article: "5-8" } },
  { title: "Büro kontrolü", detail: "Teknik belgeler, hesaplar, kararlar ve sayısal veriler kaynaklarıyla karşılaştırılır.", checks: ["Koordinat ve yüzölçümü hesaplarını kontrol et", "Karar/onay ile teknik dosyanın uyumunu kontrol et", "Pafta ve MEGSİS verilerini karşılaştır"], source: { circular: "2025/4", article } },
  { title: "Arazi kontrolü", detail: "İlgili maddede öngörülen kapsam ve örnekleme ile zemin kontrolü yapılır.", checks: ["Kontrol noktalarını doğrula", "Detay noktalarını yaygın ve dengeli seç", "Zemin ile işlem dosyasını karşılaştır"], source: { circular: "2025/4", article } },
  { title: "Hata ve noksanlık", detail: "Tespitler ilgilisine veya işlemi yapan idareye bildirilir; düzeltme sonrası yeniden kontrol edilir.", checks: ["Tespitleri kontrol formuna yaz", "Düzeltmeyi kaynak belgeler üzerinde doğrula", "Uygunluk sağlanmadan sonuçlandırma"], source: { circular: "2025/4", article: "6" } },
  { title: "Tescil ve arşiv", detail: "Tescile esas belgeler güvenli elektronik ortamda gönderilir; dönen tarih ve yevmiye bilgileri kayda alınır.", checks: ["Tescil bildirimini ve imzaları kontrol et", "Güvenli elektronik gönderimi tamamla", "Pafta/MEGSİS ve arşiv kayıtlarını güncelle"], source: { circular: "2025/4", article: "35-36" } },
];

const common2023 = (article: string, field = true): Step[] => [
  { title: "Başvuru", detail: "Hak sahipliği veya yasal ilgi ile başvuru belgeleri kontrol edilir.", checks: ["Kimlik ve yetkiyi doğrula", "İşlem türüne özgü belgeleri kontrol et", "Başvuruyu fen kayıt defterine kaydet"], source: { circular: "2023/5", article: "5-8" } },
  { title: "Hazırlık ve büro kontrolü", detail: "Arşiv, tapu planı, koordinat ve teknik bilgiler işlem türüne göre hazırlanır ve kontrol edilir.", checks: ["Pafta ve teknik belgeleri incele", "Nokta/koordinat doğruluğunu kontrol et", "İşlem özelindeki formu hazırla"], source: { circular: "2023/5", article } },
  ...(field ? [{ title: "Zemin çalışması", detail: "İşlem maddesinde tarif edilen ölçme, işaretleme veya tespit zeminde yapılır.", checks: ["Gerekli noktaları zeminde belirle", "Kontrollü ölçüyü tamamla", "Katılanların/imza sahiplerinin kayıtlarını al"], source: { circular: "2023/5" as CircularId, article } }] : []),
  { title: "Sonuç belgesi", detail: "İşleme özgü kroki, tescil bildirimi veya yazı düzenlenir ve onaylanır.", checks: ["Belge ve krokileri karşılaştır", "İmza/onayları tamamla", "İlgilisine teslim veya tapuya gönderim yap"], source: { circular: "2023/5", article } },
  { title: "Arşiv", detail: "Fen kayıt bilgileri, teslim/tescil sonucu ve teknik belgeler arşivlenir.", checks: ["Tarih ve yevmiye bilgisini kaydet", "MEGSİS/KBU kaydını tamamla", "Dosyayı arşivle"], source: { circular: "2023/5", article: "21-22" } },
];

export const processes: Process[] = [
  { id:"ayirma", title:"Ayırma / İfraz", aliases:["ifraz","ayırma"], category:"Tescile konu haritalar", circular:"2025/4", article:"26", registration:"Tescile tabi", summary:"Bir parselin iki veya daha fazla parçaya ayrılmasına ilişkin haritanın yapım ve kontrol süreci.", roles:["Mühendis","Kontrol mühendisi","Kadastro müdürü","İlgili idare","Tapu müdürlüğü"], documents:["Onaylı ayırma haritası ve işlem dosyası","Encümen kararı veya ilgili idare onayı","Ölçü krokisi ve koordinat listesi","Yüzölçümü hesapları","Değişiklik tasarımı","Tescil bildirimi"], officeChecks:["İmar planı ve karar uygunluğu","Yeni parsel numaraları","Koordinat ve yüzölçümü hesapları","Ayırma hattı ile pafta kenarlaşması"], fieldChecks:["Yeni mülkiyet sınır noktalarının kontrolü","Kontrol noktalarına dayalı ölçü","Zemin-pafta uyumu"], outputs:["Kontrol formu","Tescil bildirimi","Güncellenmiş pafta/MEGSİS kaydı"], warnings:["İmar uygulaması mümkün alanlarda öncelik parselasyon planının tescilidir.","Kaynakta açık hüküm bulunmayan belge veya süre eklenmemelidir."], steps:common2025("26") },
  { id:"birlestirme-2025", title:"Birleştirme / Tevhit", aliases:["tevhit","birleştirme"], category:"Tescile konu haritalar", circular:"2025/4", article:"26", registration:"Tescile tabi", summary:"Bitişik parsellerin bir parsel haline getirilmesine ilişkin teknik ve idari kontrol.", roles:["Mühendis","Kontrol mühendisi","Kadastro müdürü","İlgili idare","Tapu müdürlüğü"], documents:["Onaylı değişiklik dosyası","Encümen kararı/onay","Koordinat ve yüzölçümü hesapları","Tescil bildirimi"], officeChecks:["Parsellerin bitişikliği","Yüzölçümü ve koordinat kontrolü","İrtifak ve muhdesat aktarımı"], fieldChecks:["Gerektiğinde zemin sınır kontrolü"], outputs:["Yeni parsel numarası","Tescil bildirimi"], warnings:["İşlemin 2025/4 kapsamındaki dayanağı ayırma haritaları maddesindeki ifraz/tevhit hükümleriyle birlikte okunmalıdır."], steps:common2025("26") },
  { id:"yola-terk", title:"Yola Terk", aliases:["terk","yol terki"], category:"Tescile konu haritalar", circular:"2025/4", article:"27", registration:"Tescile tabi", summary:"Plan uygulaması nedeniyle taşınmazın yol alanında kalan kısmının terkine ilişkin süreç.", roles:["Mühendis","Kontrol mühendisi","Kadastro müdürü","Belediye/valilik","Tapu müdürlüğü"], documents:["Onaylı yola terk haritası","Plan/imar durumu belgesi","Encümen kararı veya onay yazısı","Ölçü krokisi","Yüzölçümü hesabı","Tescil bildirimi"], officeChecks:["Plan dayanağı","Terk sınırı ve yüzölçümü","Karar ile harita uyumu"], fieldChecks:["Terk sınırı kırık noktalarının kontrolü"], outputs:["Yola terk haritası","Tescil bildirimi"], warnings:["İşlemin plana dayalı olması esastır."], steps:common2025("27") },
  { id:"yoldan-ihdas", title:"Yoldan İhdas", aliases:["ihdas","yol fazlası"], category:"Tescile konu haritalar", circular:"2025/4", article:"28-29", registration:"Tescile tabi", summary:"Kapanan yol veya yol fazlasının ilgili mevzuata göre parsel olarak tesciline ilişkin süreç.", roles:["İlgili idare","Mühendis","Kontrol mühendisi","Kadastro müdürü","Tapu müdürlüğü"], documents:["İhdas gerekçesi ve idare kararı","İlgili kurum görüşleri","Yoldan ihdas haritası","Koordinat ve yüzölçümü hesabı","Tescil bildirimi"], officeChecks:["Yolun geldisi ve niteliği","Mülkiyet/tahsis dayanağı","Harita ve karar uyumu"], fieldChecks:["İhdas sınırının zemin kontrolü"], outputs:["Yoldan ihdas haritası","Tescil bildirimi"], warnings:["Kamulaştırmayla sağlanmış yollar için özel hüküm ayrıca değerlendirilir."], steps:common2025("28-29") },
  { id:"parselasyon", title:"Parselasyon", aliases:["imar uygulaması","18. madde","dop"], category:"Tescile konu haritalar", circular:"2025/4", article:"24-25", registration:"Tescile tabi", summary:"İmar parselleri oluşturmak amacıyla düzenlenen parselasyon haritalarının ayrıntılı kontrolü.", roles:["Uygulayıcı idare","Mühendis","Kontrol mühendisi","Kadastro müdürü","Tapu müdürlüğü"], documents:["Uygulama alanı sınır krokisi","Ayırma çapları","Özet cetveli","Dağıtım cetveli","İrtifak hakkı cetveli (varsa)","Yapı-muhdesat cetveli (varsa)","Ölçü krokileri","Encümen kararı/onay"], officeChecks:["Uygulama alanındaki tüm parseller","DOP oranı ve hesapları","Dağıtım cetvelleri","Tescil harici alanlar","İrtifak ve muhdesat aktarımı"], fieldChecks:["Ada köşeleri kontrollü ölçüsü","Detay noktası koordinat karşılaştırması","Zemin tesisleri"], outputs:["Kontrol edilmiş parselasyon haritası","Tescile esas cetveller"], warnings:["Hatalı veya yasal üst sınırı aşan DOP giderilmezse işlem reddedilir."], steps:common2025("24-25") },
  { id:"kamulastirma", title:"Kamulaştırma", aliases:["kamulaştırma haritası","2942"], category:"Tescile konu haritalar", circular:"2025/4", article:"22-23", registration:"Tescile tabi", summary:"Kamulaştırmayı yapan idarenin hazırladığı haritanın büro ve arazi kontrolü ile tescile hazırlanması.", roles:["Kamulaştırmayı yapan idare","Mühendis","Kontrol mühendisi","Kadastro müdürü","Tapu müdürlüğü"], documents:["İdarece onaylı kamulaştırma haritası","İki nüsha işlem dosyası","Kamulaştırma kararı","Ölçü krokileri","Her parsel için tescil bildirimi"], officeChecks:["Kararın kontrol edilmiş dosyaya uygunluğu","Parsellerde sonradan düzeltme/değişiklik olup olmadığı","Yüzölçümü ve sayısal harita"], fieldChecks:["Sınır kesişim noktalarının en az yüzde beşi","Yaygın ve dengeli kontrol ölçüsü"], outputs:["Kontrol edilmiş işlem dosyası","Parsel bazlı tescil bildirimi"], warnings:["Kamulaştırma kararı gelmeden kontrol yapılabilir; tescile gönderim karar ve güncellik kontrolünden sonra tamamlanır."], steps:common2025("22-23") },
  { id:"toplulastirma", title:"Toplulaştırma", aliases:["arazi toplulaştırması","dağıtım"], category:"Tescile konu haritalar", circular:"2025/4", article:"33-34", registration:"Tescile tabi", summary:"Toplulaştırma uygulama alanı ve dağıtım sonuçlarının teknik kontrolü.", roles:["Uygulayıcı kurum","Mühendis","Kontrol mühendisi","Kadastro müdürü","Tapu müdürlüğü"], documents:["Uygulama alanı sınır krokisi","Blok ve parsel planları","Dağıtım cetvelleri","Derecelendirme/dağıtım belgeleri","Ölçü krokileri","Tescil bildirimleri"], officeChecks:["Uygulama içi/dışı parseller","Dağıtım ve yüzölçümü dengesi","İrtifak ve muhdesat aktarımı"], fieldChecks:["Yeni blok/parsel köşe kontrolleri","Kontrol noktalarına dayalı ölçü"], outputs:["Kontrol edilmiş toplulaştırma haritası","Tescile esas belgeler"], warnings:["Uygulama alanı sınırı ve uygulama dışı bırakılan parseller birlikte kontrol edilmelidir."], steps:common2025("33-34") },
  { id:"koy-yerlesim", title:"Köy Yerleşim Haritaları", aliases:["köy yerleşme alanı","442"], category:"Tescile konu haritalar", circular:"2025/4", article:"30", registration:"Tescile tabi", summary:"Kesinleşen köy yerleşim haritalarının komisyon kararı ve teknik dosyayla kontrolü.", roles:["Köy yerleşim yeri tespit komisyonu","İlgili idare","Mühendis","Kontrol mühendisi","Kadastro müdürü"], documents:["Kesinleşmiş köy yerleşim haritası","Komisyon kararı","Parsel listeleri","Ölçü ve koordinat belgeleri","Tescil bildirimi"], officeChecks:["Komisyon kararı-harita uyumu","Parsel ve yüzölçümü bilgileri"], fieldChecks:["Gerekli zemin ve sınır kontrolü"], outputs:["Kontrol edilmiş köy yerleşim haritası","Tescil bildirimi"], warnings:["Orman ve mera haritaları ayrı maddelerde düzenlenmiştir."], steps:common2025("30") },
  { id:"orman", title:"Orman Haritaları", aliases:["orman tahdidi","orman kadastrosu"], category:"Tescile konu haritalar", circular:"2025/4", article:"31", registration:"Tescile tabi", summary:"Orman tahdidi/kadastrosu çalışmalarıyla üretilen haritaların kontrolü.", roles:["Orman idaresi","Kontrol mühendisi","Kadastro müdürü","Tapu müdürlüğü"], documents:["Orman kadastro/tahdit haritası","Kesinleşme belgeleri","Teknik dosya","Tescil bildirimi"], officeChecks:["Kesinleşme ve teknik uyum","Pafta ve koordinat kontrolü"], fieldChecks:["Gerekli sınır kontrolü"], outputs:["Kontrol edilmiş harita","Tescil bildirimi"], warnings:["İşlem yalnızca Madde 31 ve atıf yapılan özel mevzuat kapsamında değerlendirilir."], steps:common2025("31") },
  { id:"mera", title:"Mera Haritaları", aliases:["mera tahdidi","mera kadastrosu"], category:"Tescile konu haritalar", circular:"2025/4", article:"32", registration:"Tescile tabi", summary:"Mera tahdidi/kadastrosu çalışmalarıyla üretilen haritaların kontrolü.", roles:["Mera komisyonu/ilgili idare","Kontrol mühendisi","Kadastro müdürü","Tapu müdürlüğü"], documents:["Mera haritası","Tahsis/tahdit ve kesinleşme belgeleri","Teknik dosya","Tescil bildirimi"], officeChecks:["Karar ve harita uyumu","Teknik dosya kontrolü"], fieldChecks:["Gerekli sınır kontrolü"], outputs:["Kontrol edilmiş harita","Tescil bildirimi"], warnings:["İşlem yalnızca Madde 32 ve atıf yapılan özel mevzuat kapsamında değerlendirilir."], steps:common2025("32") },
  { id:"sinirlandirma", title:"Sınırlandırma Haritaları", aliases:["tapulu taşınmaz sınırlandırma"], category:"Tescile konu haritalar", circular:"2025/4", article:"21", registration:"Tescile tabi", summary:"Tapu ve tasarruf sınırlarının katılımcılarla zeminde belirlenmesi ve ölçülmesi.", roles:["Kadastro müdürü","Kontrol mühendisi","Kadastro üyesi","Malik/temsilci","Bilirkişiler"], documents:["Tapu kaydı ve planı","Sınırlandırma krokisi","Zemin tespit tutanağı","Ölçü krokisi","Koordinat ve yüzölçümü hesapları","Tescil bildirimi"], officeChecks:["Tapu tatbikatı","Hesaplanan ve kayıtlı yüzölçümü karşılaştırması"], fieldChecks:["Tapu ve tasarruf sınırlarının belirlenmesi","Katılımcı imzaları","Yer kontrol noktaları ve detay ölçüsü"], outputs:["Sınırlandırma krokisi","Zemin tespit tutanağı","Tescil bildirimi"], warnings:["Hesaplanan alan tapu alanından büyükse yargı kararı olmadan tescil edilemez; dosya açıklamayla iade edilir."], steps:common2025("21") },
  { id:"plan-ornegi", title:"Plan Örneği", aliases:["çap","pafta örneği"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"14-15", registration:"Tescile tabi değil", summary:"Parselin tescilli tapu planından örnek hazırlanması ve ilgilisine verilmesi.", roles:["Kadastro müdürlüğü","LİHKAB","Lisanslı mühendis"], documents:["Başvuru ve kimlik/yetki belgeleri","Harç/ücret bilgisi","İstem belgesi","Plan örneği"], officeChecks:["Hak sahipliği/yasal ilgi","Pafta ve güncel teknik veriler","Plan örneği içeriği"], fieldChecks:[], outputs:["Plan örneği","İstem belgesi/teslim kaydı"], warnings:["Normal şartlarda arazi kontrolü bulunmaz."], steps:common2023("14-15",false) },
  { id:"yer-gosterme", title:"Yer Gösterme", aliases:["parsel yer gösterme","bağımsız bölüm yer gösterme"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"16", registration:"Tescile tabi değil", summary:"Parsel veya bağımsız bölümün yerinin zeminde ilgilisine gösterilmesi.", roles:["LİHKAB/kadastro teknik personeli","Lisanslı mühendis"], documents:["Başvuru ve kimlik/yetki belgeleri","Pafta örneği","Yer gösterme krokisi","İstem belgesi"], officeChecks:["Parsel ve pafta bilgilerinin hazırlanması","Gerekli koordinatların kontrolü"], fieldChecks:["Parselin zeminde gösterilmesi","Yer gösterme krokisinin düzenlenmesi"], outputs:["Yer gösterme krokisi","Teslim/imza kaydı"], warnings:["Yer gösterme, sınır aplikasyonu yerine geçmez."], steps:common2023("16",true) },
  { id:"aplikasyon", title:"Aplikasyon", aliases:["aplikasyon krokisi","sınır aplikasyonu"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"17", registration:"Tescile tabi değil", summary:"Tescilli tapu planındaki mülkiyet, irtifak veya yol sınırlarının zemine uygulanması.", roles:["Lisanslı mühendis","Tekniker/teknisyen","Kadastro teknik personeli"], documents:["Başvuru ve kimlik/yetki belgeleri","Tapu planı ve teknik belgeler","Aplikasyon krokisi","Ölçü kayıtları"], officeChecks:["Tapu planı ve nokta konum doğruluğu","Aplikasyon elemanları","Yanılma sınırı değerlendirmesi"], fieldChecks:["Sınır noktalarının zemine uygulanması","Kontrollü ölçü","Aplikasyon krokisi imzaları"], outputs:["Aplikasyon krokisi","Teslim kaydı"], warnings:["Aplikasyon uzunluğu 500 metreyi geçemez hükmü Madde 17 içinde yer alır."], steps:common2023("17",true) },
  { id:"cins-degisikligi", title:"Cins Değişikliği", aliases:["vasıf değişikliği","yapılı hale gelme","yapısız hale gelme"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"18", registration:"Tescile tabi", summary:"Taşınmazın yapılı/yapısız hale gelmesi veya vasfının değişmesine ilişkin kapsamlı işlem.", roles:["Lisanslı mühendis","Kadastro müdürlüğü","İlgili idare","Tapu müdürlüğü"], documents:["İşlem türüne uygun idare yazısı/izin belgesi","Ölçü krokisi","Koordinat ve yüzölçümü belgeleri","Tescil bildirimi","Özel duruma ilişkin uygun görüşler"], officeChecks:["Cins değişikliği alt türü","İdari belge ve yapı bilgileri","Taşkın kullanım incelemesi"], fieldChecks:["Yapı/tesis ve parsel sınırı ilişkisi","Tescilli ölçülerle uygunluk"], outputs:["Tescil bildirimi","Güncellenmiş pafta/MEGSİS"], warnings:["Madde 18 çok sayıda özel durum içerir; seçimler dosyanın niteliğine göre ayrıca değerlendirilmelidir."], steps:common2023("18",true) },
  { id:"irtifak", title:"İrtifak Hakkı", aliases:["irtifak tesisi","irtifak terkini","geçit hakkı"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"19", registration:"Tescile tabi", summary:"İrtifak güzergâhının ölçülmesi, değişiklik tasarımının onayı ve tescili/terkini.", roles:["Lisanslı mühendis","Kadastro müdürlüğü","Belediye/valilik","Tapu müdürlüğü"], documents:["Leh ve aleyhe beyanlar","İki nüsha değişiklik tasarımı","Encümen kararı ve onay","Ölçü krokisi","Tescil bildirimi"], officeChecks:["Leh/aleyh taşınmazlar","Güzergâh koordinatları","Onay kararı ve tescil bildirimi"], fieldChecks:["İlgililerce işaretlenen güzergâhın ölçüsü"], outputs:["Değişiklik tasarımı","Tescil bildirimi","MEGSİS kaydı"], warnings:["Tescil harici alan ve kamulaştırma kapsamındaki irtifaklar için farklı hükümler vardır."], steps:common2023("19",true) },
  { id:"birlestirme-2023", title:"Birleştirme (Talebe Bağlı)", aliases:["tevhit","parsel birleştirme"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"20", registration:"Tescile tabi", summary:"Bitişik taşınmazların talebe bağlı olarak birleştirilmesi ve tescile hazırlanması.", roles:["Lisanslı mühendis","Kadastro müdürlüğü","Belediye/valilik","Tapu müdürlüğü"], documents:["İki nüsha değişiklik tasarımı","Encümen kararı/onay","Yüzölçümü ve koordinat hesabı","Tescil bildirimi"], officeChecks:["Parsellerin bitişikliği","Parsel bazlı yüzölçümü ve nokta konum doğruluğu","İrtifak haklarının aktarımı"], fieldChecks:["Hata veya sınır belirsizliğinde gerekli kontrol"], outputs:["Yeni parsel numarası","Tescil bildirimi"], warnings:["Yanılma sınırı veya nokta konum hatası önce hata mevzuatına göre düzeltilir."], steps:common2023("20",true) },
  { id:"muhdesat-cinse", title:"Muhdesatın Cinse Taşınması", aliases:["muhdesat cinse taşıma","muhtesat"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"18/2", registration:"Tescile tabi", summary:"Beyanlar sütunundaki muhdesat ile mülkiyet aynı kişide birleştiğinde muhdesatın taşınmaz cinsine taşınması.", roles:["LİHKAB/kadastro müdürlüğü","Lisanslı mühendis","Tapu müdürlüğü"], documents:["Tapu kaydı ve muhdesat beyanı","Zemin tespit belgeleri","Tescil bildirimi","Tarımsal muhdesatta uygunluk yazısı"], officeChecks:["Mülkiyet ve muhdesat sahibinin aynı kişi olması","Tescilli ölçü değerleri"], fieldChecks:["Muhdesatın zemindeki varlığı","Yıkılıp yeniden yapılma veya ilave kat durumu"], outputs:["Tescil bildirimi","Muhdesat kaydının terkini"], warnings:["Yıkılıp yeniden yapıldığı tespit edilirse muhdesat cinse taşınmaz."], steps:common2023("18/2",true) },
  { id:"muhdesat-terk", title:"Muhdesatın Terkini", aliases:["muhdesat terki","muhtesat terkini"], category:"Talebe bağlı işlemler", circular:"2023/5", article:"18/3", registration:"Duruma göre", summary:"Zeminde mevcut olmayan kayıtlı muhdesatın tapu kaydından terkin edilmesi.", roles:["LİHKAB/kadastro müdürlüğü","Lisanslı mühendis","Tapu müdürlüğü"], documents:["Başvuru ve tapu kaydı","Zemin tespit belgesi","Ek-22 yazısı (uygunsa)","Tescil bildirimi (paftaya işlenmişse)","Tarımsal muhdesatta uygunluk yazısı"], officeChecks:["Muhdesatın paftaya işlenip işlenmediği","Tescil bildirimi veya yazı yolunun seçimi"], fieldChecks:["Muhdesatın zeminde mevcut olmadığının tespiti"], outputs:["Tescil bildirimi veya tapu müdürlüğüne yazı","Terkin kaydı"], warnings:["Paftaya işlenmemiş muhdesatta tescil bildirimi düzenlenmez; yazıyla bildirim yapılır."], steps:common2023("18/3",true) },
];

export const definitions = [
  ["Aplikasyon","Tescilli tapu planındaki mülkiyet, irtifak hakkı ve yol sınırlarının zemine uygulanması.","2023/5","3"],
  ["BÖHHBÜY","Büyük Ölçekli Harita ve Harita Bilgileri Üretim Yönetmeliği.","2025/4","3"],
  ["KBU","Kadastro Bilgi Sistemi kapsamındaki başvuru ve işlem ortamı.","2023/5","3"],
  ["Kontrollü ölçü","Bir noktanın konumunu bağımsız veya ek ölçülerle doğrulayan ölçme yaklaşımı.","2025/4","3"],
  ["LİHKAB","Lisanslı Harita Kadastro Mühendislik Bürosu.","2023/5","3"],
  ["MEGSİS","Mekânsal Gayrimenkul Sistemi.","2025/4","3"],
  ["SHKMMB","Serbest Harita ve Kadastro Mühendislik Müşavirlik Bürosu/şirketi.","2025/4","3"],
  ["Tescil bildirimi","Tescile konu değişikliğin teknik ve tescil bilgilerini gösteren belge.","2025/4","3"],
  ["TUREF","Türkiye Ulusal Referans Çerçevesi.","2025/4","3"],
  ["Yanılma sınırı","Ölçü ve hesaplarda mevzuatın kabul ettiği azami fark sınırı.","2023/5","3"],
] as const;

export const articleIndex = [
  { circular:"2025/4" as const, articles:["1 Amaç","2 Dayanak","3 Tanımlar","4 Sorumluluk","5-12 Başvuru ve genel kontrol","13-20 Teknik esaslar","21 Sınırlandırma","22-23 Kamulaştırma","24-25 Parselasyon","26 Ayırma","27 Yola terk","28-29 Yoldan ihdas","30 Köy yerleşim","31 Orman","32 Mera","33-34 Toplulaştırma","35-36 Tescil ve arşiv","37-40 Son hükümler"] },
  { circular:"2023/5" as const, articles:["1 Amaç","2 Dayanak","3 Tanımlar","4 Sorumluluk","5-13 Başvuru ve genel esaslar","14-15 Plan örneği","16 Yer gösterme","17 Aplikasyon","18 Cins değişikliği ve muhdesat","19 İrtifak hakkı","20 Birleştirme","21-22 Tescil ve arşiv","23-25 Son hükümler"] },
];
